### ISSUE TITLE
failing test: TestRoundTripRaw(with -race flag)

### ISSUE THREAD

**Issue by galargh** [ipld/go-ipld-prime-proto#25]
While looking at the unmerged web3-bot PR(https://github.com/ipfs/go-ds-sql/pull/23), I have noticed that `go test -v -race ./...` fails with:
```
=== RUN   TestRoundTripRaw/decoding
fatal error: checkptr: pointer arithmetic result points to invalid allocation
```
in this repository. It's consistent between runs on go1.16 and go1.17.

**Comment by mvdan** [comment]
Closing as per https://github.com/ipld/go-ipld-prime-proto/issues/23 :) No point in fixing up CI if we're going to archive the repo for good.
